[package]
name = "NexTeMP"
version = "1.0.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.134"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
debug = 0